"""empty message

Revision ID: b90717c59669
Revises: 92a1392a33d1
Create Date: 2019-10-08 19:21:50.712272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90717c59669'
down_revision = '92a1392a33d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'supermarkets', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supermarkets', type_='unique')
    # ### end Alembic commands ###
